server:
  port: 18080

spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/notice_app
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    user:
      name: "admin"
      password: "admin"
logging:
  level:
    org.hibernate.SQL: debug